add semigroup instances
tsurucapital/euphoria pull request #24
Opened 2018-11-07 07:26 UTC by fumieval

2018-11-15 05:36 UTC, maoe requested changes
I think this patch still fails with GHC 8.6. You can rebase it onto #25 to see which versions of GHC fail.

I got this with 8.6.2:
```
[2 of 4] Compiling Data.EnumSet     ( Data/EnumSet.hs, dist/build/Data/EnumSet.o )

Data/EnumSet.hs:24:15: error:
    • No instance for (GHC.Base.Semigroup (EnumSet k))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid (EnumSet k))
   |
24 |     (Eq, Ord, Monoid, Typeable, Data, NFData)
   |               ^^^^^^
cabal: Failed to build enummapset-th-0.6.1.1 (which is required by
euphoria-0.8.0.0). See the build log above for details.
```

2018-11-15 05:36 UTC, maoe commented on euphoria.cabal
> +                     , semigroups
Should we apply https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4#base-4.11.0.0?

2020-07-22 06:12 UTC, maoe commented on euphoria.cabal
> +                   , GHC == 8.10.3
8.10.1?

2020-07-22 06:15 UTC, fumieval commented on euphoria.cabal
> +                   , GHC == 8.10.3
it was some mirage...

2020-08-04 03:55 UTC, maoe approved these changes

2020-08-04 03:55 UTC, maoe commented
LGTM

2020-08-04 03:58 UTC, merged